name: Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node.js ${{ matrix.node }}
    strategy:
      matrix:
        node: ['10.x', '11.x', '12.x', '13.x', '14.x', '15.x', '16.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: yarn test:ci
